/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DirectoryCardCmp: typeof import('./src/components/DirectoryCardCmp.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    MainCmp: typeof import('./src/components/layout/MainCmp.vue')['default']
    NavCmp: typeof import('./src/components/layout/NavCmp.vue')['default']
    NavItemCmp: typeof import('./src/components/layout/NavItemCmp.vue')['default']
    RemarkCmp: typeof import('./src/components/RemarkCmp/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
